// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Here UpdateAccount is the name of the function in generated go code :one means return one row
	// sqlc.arg(amount) allows use to use the amount variable in generated go code, because balance doesn't make sense
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeleteAccount(ctx context.Context, id int64) error
	// the * means return all the columns
	// There was a bug here during concurrent transactions:
	// when we read the row, we need to lock it from begin to the commit of the transaction
	// otherwise, the other transaction will get incorrect info because the previous transaction is not completed yet
	GetAccount(ctx context.Context, id int64) (Account, error)
	// Here GetAccount is the name of the function in generated go code :one means one row
	// we should use this function instead for transaction
	// SELECT * FROM accounts WHERE id = $1 LIMIT 1 FOR UPDATE; [ this is not ideal ]
	// however, this will create exclusive lock on the row,
	//which means no other transaction can read or write to the row until the current transaction is committed
	// it blocks UPDATE, DELETE and INSERT operations on the row
	// a better way is to use FOR NO KEY UPDATE
	// this only create weaker lock while allow INSERT, while still block modify key column and DELETE
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	// LIMIT $1 enable pagination so that we only display certain number of rows
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
